services:
  actix:
    build: .
    ports:
      - "8081:8081"
    environment:
      - RUST_LOG=debug
      - MONGO_URI=mongodb://mongo:27017/hactix_db
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
